@startuml

title UAV pathing activity

partition Path_Planning {
(*) --> "Get next task" as next
--> "Compute Dubin's Path"
}

partition Path_Following {
-r-> "Step kinematics" as step

step --> if "At waypoint?" then
  -->[Yes] if "At last waypoint?" then
            -->[Yes] next
          else
            -->[No] "Iterate Waypoint"
            -l-> step
          endif
else
  -->[No] step
endif
}


@enduml