@startuml

(*) -> "Update kinematics"
-r-> "Update pathing"
-r-> "Relay communications"
-d-> "Merge incoming belief states"
-l-> "Process contracts"
-l-> "Process current task"

if "Internal belief changed" then
  -d->[true] "Task updated belief?"
  -> (*)
else
  ->[false] (*)
endif

@enduml